name: build-v5

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 */6 * *'
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-v5.yml"
      - "dev/v5/Dockerfile"
      - "dev/v5/entrypoint.sh"

jobs:
  build-v5:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Convert tags to lowercase
        run: |
          docker_name="${{ secrets.DOCKERHUB_USERNAME }}"
          repository="${{ github.repository }}"
          repo_name="${repository##*/}"

          dockerhub_tag="${docker_name}/${repo_name}"
          ghcr_tag="ghcr.io/${{ github.repository }}"

          echo "dockerhub_tag=${dockerhub_tag,,}" >> $GITHUB_ENV
          echo "ghcr_tag=${ghcr_tag,,}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:dev/v5"
          file: Dockerfile
          push: true
          platforms: linux/arm, linux/arm64, linux/amd64, linux/ppc64le, linux/s390x, linux/riscv64
          tags: |
            ${{ env.dockerhub_tag }}:v5
            ${{ env.ghcr_tag }}:v5